### ISSUE TITLE
Alarm control unit not available

### ISSUE THREAD

**Issue by leciuk81** [petrleocompel/hikaxpro_hacs#17]
Hi Petr,
can you help me?
I can log in and set the central locally without authentication problems.
I can install and configure the addon from hacs but then the control panel can’t find the alarm central.
![image](https://user-images.githubusercontent.com/126766794/222390886-dd4121f3-4149-4cbb-9a1a-5b4fa90302ae.png)
![Screenshot_20230302_110145_Home Assistant](https://user-images.githubusercontent.com/126766794/222396935-cb926921-07d5-4578-813e-330a6eb9fb2f.jpg)

Modello dispositivo:DS-PWA96-M-WE
Versione Firmware:V1.2.8 build 230110
Versione Web:V4.25.1 build 221212
sensors:
DS-PDMCX-E-WE
DS-PDPG12P-EG2-WE
DS-PDPC12P-EG2-WE
DS-PDMCK-EG2-WE
DS-PDMC-EG2-WE

sirens:
DS-PS1-I-WE
DS-PS1-E-WE

tag readers:
DS-PT1-WE

wireless keyfob:
DS-PKF1-WE

I attach the debug
[error_log.txt](https://github.com/petrleocompel/hikaxpro_hacs/files/10869995/error_log.txt)

**Comment by petrleocompel** [comment]
I see main problem. `AccessModuleType` and that was fixed with 0.6.4.
Next thing is `Invalid detector type magnetShockDetector` but we are not crashing on this.
Please update to version 0.6.4 and restart homeassinstant.

**Comment by leciuk81** [comment]
You are great!!!!
Thank you very much.
It seems to work fine now
![2](https://user-images.githubusercontent.com/126766794/222404904-02b53941-6134-48d8-b05d-ff8b55bada7f.jpg)
I still don't see the status of the batteries but it's a minor problem
![1](https://user-images.githubusercontent.com/126766794/222405023-dfd04ff2-c3ad-4ff6-ae45-f87b8e3086e9.jpg)

**Comment by petrleocompel** [comment]
Everytime if something is not working. Issue + log. We will sort it out.

**Comment by petrleocompel** [comment]
More type of detectors are on the way.

**Comment by petrleocompel** [comment]
Also batteries are issue #16, currently working on it how to implement this.
